language: android

jdk:
 - oraclejdk7
 - oraclejdk8

android:
  components:
    - build-tools-21.1.1
    - android-19
  licenses:
    - android-sdk-license-5be876d5

script:
  - ./gradlew clean check

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
